### ISSUE TITLE
Error on ImportMeta types

### ISSUE THREAD

**Issue by bramaudi** [solidui/vite-plugin-solid#10]
I follow the code below to opt out HMR

``` js
if (import.meta.hot) {
  import.meta.accept();
  import.meta.dispose(dispose);
}
```

But it got error on type-checking:

```
Property 'accept' does not exist on type 'ImportMeta'.
```

Did you mean `import.meta.hot.accept()` & ` import.meta.hot.dispose(dispose)`?

**Comment by amoutonbrady** [comment]
Hey! Yes this is definitely a typo. I'll update the Readme with the proper syntax. Thanks (and sorry for the delayed answer).
